# Generated by Django 5.0.3 on 2026-05-20 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitylog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="activitylog",
            name="changes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Field-level change tracking: {"field": {"old": X, "new": Y}}',
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address of the request that triggered this log entry.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user_agent",
            field=models.CharField(
                blank=True,
                default="",
                help_text="User-agent string from the request headers.",
                max_length=512,
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["actor", "created_at"], name="audit_activ_actor_i_5122be_idx"
            ),
        ),
    ]
