# Generated by Django 5.2.14 on 2026-05-07 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="available_countries",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of countries where this course is available",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="intake_months",
            field=models.CharField(
                blank=True, help_text="e.g. January, May, September", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="counselor",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned counselor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="counseled_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="poc",
            field=models.ForeignKey(
                blank=True,
                help_text="Point of contact (counselor)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="poc_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["country", "name"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="crm.school",
            ),
        ),
        migrations.CreateModel(
            name="StudentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("application_submitted", "Application Submitted"),
                            ("document_uploaded", "Document Uploaded"),
                            ("message_received", "Message Received"),
                            ("preference_saved", "Preference Saved"),
                            ("profile_updated", "Profile Updated"),
                            ("status_changed", "Status Changed"),
                            ("note_added", "Note Added"),
                            ("meeting_scheduled", "Meeting Scheduled"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="crm.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_country", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_preferences",
                        to="crm.course",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_preferences",
                        to="crm.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="crm.student",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["is_active", "country"], name="crm_school_is_acti_751cd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentactivity",
            index=models.Index(
                fields=["student", "created_at"], name="crm_student_student_e5c64c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentpreference",
            index=models.Index(
                fields=["student"], name="crm_student_student_eacd0d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentpreference",
            unique_together={("student", "school", "course")},
        ),
    ]
