# Generated by Django 5.0.3 on 2026-05-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0004_studentassignedschool_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="deadline",
            field=models.DateField(
                blank=True, help_text="General application deadline", null=True
            ),
        ),
    ]
