# Generated by Django 5.0.3 on 2026-05-20 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0017_soft_delete_documents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="studentschooldocument",
            name="crm_student_student_ac7930_idx",
        ),
        migrations.RenameIndex(
            model_name="studentprofiledocument",
            new_name="crm_student_student_347df9_idx",
            old_name="crm_studentprofiledoc_student_cat_idx",
        ),
        migrations.RenameIndex(
            model_name="studentschooldocument",
            new_name="crm_student_student_527ffd_idx",
            old_name="crm_studen_student_school_cat_idx",
        ),
        migrations.AddField(
            model_name="student",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                help_text="When set, this student is considered deleted and hidden from all views.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="followup",
            index=models.Index(
                fields=["assigned_to", "status"], name="crm_followu_assigne_750ed7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["assigned_to", "status"], name="crm_lead_assigne_36bf8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["counselor", "is_active"], name="crm_student_counsel_91c8e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["deleted_at"], name="crm_student_deleted_64b34a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentassignedschool",
            index=models.Index(
                fields=["school"], name="crm_student_school__1de02b_idx"
            ),
        ),
    ]
