# Generated by Django 5.0.3 on 2026-05-23 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0020_student_email_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="father_phone",
            field=models.CharField(
                blank=True,
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number (6–15 digits, optional leading +).",
                        regex="^\\+?[0-9]{6,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="mother_phone",
            field=models.CharField(
                blank=True,
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number (6–15 digits, optional leading +).",
                        regex="^\\+?[0-9]{6,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number (6–15 digits, optional leading +).",
                        regex="^\\+?[0-9]{6,15}$",
                    )
                ],
            ),
        ),
    ]
