# Generated by Django 5.0.3 on 2026-06-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0022_student_reference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentreference",
            name="file_path",
        ),
        migrations.AddField(
            model_name="studentreference",
            name="file_data",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="studentreference",
            name="file_mime",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
